drivendataorg/cookiecutter-data-science

docs/docs/index.md, {{ cookiecutter.repo_name }}/README.md
@pjbull Here is a PR that corresponds to #12 . let me know if you want the base filename to change to something else.
=> adds visualization directory to src

{{ cookiecutter.repo_name }}/.gitignore
Update .gitignore file to avoid ignoring the src/data folder
=> Update .gitignore file to avoid ignoring the src/data folder

cookiecutter.json
Closes #52
Sets default `repo_name` to be lowercase.
=> #52 Make default repo_name lowercase

README.md
The file structure is an essential part of the provided benefit and should be in the readme file.
=> Add directory structure to README, improves #10

{{ cookiecutter.repo_name }}/Makefile
This is one of a series of PRs that relate to #72.
Just to be sure I think it's nice to have the essential Python installation tools up-to-date all the time.
=> feat: upgrade essentials before requirement

cookiecutter.json, {{ cookiecutter.repo_name }}/LICENSE
Hi @pjbull,
This change alone would fix #102! Not that we couldn't take it even further...
Thanks for sharing your thoughts.
Best,
Marianne
=> Offer accurate, open-ended licensing suggestions.

{{ cookiecutter.repo_name }}/.gitignore
These files are created when new folders are created within MacOSX directories.
=> Added _.DS_Store_ OSX directory file extension

{{ cookiecutter.repo_name }}/requirements.txt, {{ cookiecutter.repo_name }}/setup.py
@isms I think this is the minimum bar that addresses #101.
If it looks good, I'll add some tweaks to the docs as well to update the notebook imports.
=> Create and install src as Python package

{{ cookiecutter.repo_name }}/Makefile
=> Rename make target `show-help` to `help`

docs/mkdocs.yml
=> Add edit_uri to mkdocs.yml

{{ cookiecutter.repo_name }}/.gitignore
Change .gitignore so that temporary vim files are not tracked.
=> Ignore vim temp files: swp, swo

{{ cookiecutter.repo_name }}/.gitignore
=> Add .mypy_cache/ to .gitignore

README.md, docs/docs/index.md
=> Change archived asciinema example

{{ cookiecutter.repo_name }}/Makefile
This is a proposed revision to fix #115
=> Added source and destination to Make data target

docs/docs/index.md
This needs to be merged before #162
=> Fix find-replace error

index.html
=> Changed link of Edit on github to github root repository

docs/docs/using-the-template.md
=> Add documentation about Make on Windows

dev-requirements.txt, pyproject.toml
This is what we used to ship v2.
- add build and twine
- update category string to match PyPI
=> Add needed requirements and update for PyPI deploy

.github/workflows/tests.yml, HISTORY.md, README.md, docs/docs/index.md, docs/docs/v1.md, pyproject.toml
=> Deprecate Python 3.8 support, add 3.13 support and tests

README.md, docs/docs/index.md
=> Add badges to README and docs homepage

docs/docs/using-the-template.md
Fix typo in using-the-template.md.
=> Fix typo in using-the-template.md

docs/docs/contributing.md
This PR adds documentation to  regarding guidelines for contributing and how to request new tools, addressing issue #384.
=> Docs: Add guidelines for contributing and requesting tools
