- {{ cookiecutter.repo_name }}/Makefile
By default pip will warn of requirements which are already installed, this fact coupled with the fact that `make data` depends on `requirements` (a good thing) generates a ton of uninteresting output for the task `make data`. I'm proposing pip be made silent as we aren't losing any transparency because make will still print `pip install -q -r requirements.txt` to the command line when executing `make data`.
The second change adds the virtualenv directories which will contain python code to the exclude list for flake8 so as to not generate linter warnings about code not written by the data scientists.
> Less Verbose make Commands (data, lint)

- {{ cookiecutter.repo_name }}/.gitignore
I guess the correct way of ignoring the data folder is: `data/` rather than `./data/`
> Update .gitignore file to ignore the data folder

- {{ cookiecutter.repo_name }}/docs/commands.rst
The current Makefile template doesn't use `s3cmd` anymore but `aws s3 sync`.
> Update commands doc.

- {{ cookiecutter.repo_name }}/Makefile
- {{ cookiecutter.repo_name }}/src/data/make_dataset.py
With this patch `make lint` wouldn't report errors in newly created projects.
> Make `make lint` work for new projects.

- cookiecutter.json
- {{ cookiecutter.repo_name }}/Makefile
- {{ cookiecutter.repo_name }}/test_environment.py
This pull request adds  several enhancements:
* [Default rule](https://gist.github.com/klmr/575726c7e05d8780505a) in the Makefile to show the other commands with their descriptions from the comments above.
* Additional variable to the template for setting a python interpreter (python vs python3)
* 2 new Makefile commands
- `create_environment` new virtualenv with the correct interpreter using `virtualenvwrapper`(optional)
- `test_environment` tests the python environment before installing requirements
> Makefile help, specify python interpreter, test environment

- {{ cookiecutter.repo_name }}/.gitignore
Closes #53 
I rename IPython to Jupyter in a comment in the template `.gitignore`.
> #53 Rename IPython to Jupyter

- {{ cookiecutter.repo_name }}/Makefile
On Mac with GNU Make 3.81 I had to change `findstr` to `findstring` to get the makefile to correctly read the python version number.
> Changed findstr to findstring

- .gitignore
- cookiecutter.json
- docs/docs/index.md
- tests/test_creation.py
- {{ cookiecutter.repo_name }}/Makefile
Allows easy profile mangement for users working on multiple projects with multiple AWS access keys. I also fixed one of the tests, which was currently failing by default.
> Added support for multiple AWS profiles

- {{ cookiecutter.repo_name }}/Makefile
When running `make create_environment` with `PYTHON_INTERPRETER = python3` and `HAS_CONDA=True`, we should use the latest stable python3, instead of python3.5
> Use latest stable python3 in conda create

- {{ cookiecutter.repo_name }}/.gitignore
Added Spyder and VSCode project folders to .gitignore:
.vscode/
.spyproject/
> Spyder and VSCode project folders in .gitignore

- {{ cookiecutter.repo_name }}/Makefile
This is one of a series of PRs that relate to #72.
> refactor: restrict linting to `src` directory

- {{ cookiecutter.repo_name }}/Makefile
This is one of a series of PRs that relate to #72.
These are the commands used by the oh-my-zsh `pyclean` command. Seem well defined and safe to me.
> refactor: extend the `make clean` command

- {{ cookiecutter.repo_name }}/setup.py
In `setup.py` the version is currently `0.0.1`. For [semantic versioning](https://semver.org/) the version numbers should correspond to `MAJOR.MINOR.PATCH`, with `PATCH` only being incremented for bugfixes. Since the initial development is not a bugfix but the first minor version, I think it would help encourage best practices in versioning to change the initial version in the template to `0.1.0`.
Thoughts?
> Change version in setup.py to 0.1.0

- .gitignore
- tests/conftest.py
- tests/test_creation.py
Part of our Data Days for Good initiative was to work on this repo. One of the requested additions was fleshing out the setup tests a little bit more to test for what would happen if user input was introduced. This was mentioned by Isaac. I have separated out the fixture and put it in it's own file, which is discoverable by `pytest` and mentioned in the docs. I have also increased the scope of creating the temp directory to be a class scope so it doesn't have to create it and tear it down after every function call. Lastly I also test for certain conditions given user input.
> Expand Setup Tests

- {{ cookiecutter.repo_name }}/.gitignore
Unless there is some odd comma syntax I don't know about, it seems there is a typo in the .gitignore file.
> fixed gitignore typo

- {{ cookiecutter.repo_name }}/Makefile
Fixed typo in Makefile, section "Set up python interpreter environment": intalled --> installed
> Fixed: Typo in Makefile

- {{ cookiecutter.repo_name }}/docs/commands.rst
Hopefully this is the right place for this, apologies if not. This is my first attempt contributing to this project. I noticed in a comment in #162 that ```commands.rst``` doesn't build with the new cloud provider options. I think this resolves the issue, but it's hard for me to test completely as I hit later errors in the project. This does seem to resolve that specific error at least.
If there's any additional work I can do to help with the merge process, or if there's a better place to submit this please let me know.
Thanks
> handle multiple data providers

- README.md
- docs/docs/index.md
- {{ cookiecutter.repo_name }}/README.md
Use https://tox.readthedocs.io/ instead of insecure and somehow confused  tox.testrun.org.
This was already mentioned in the issues and it looks like there was respective pull request, but for a reason I don't see better link to the tox project.
> Tox reference

- tests/test_creation.py
Casting Path objects to strings due to an issue with `WindowsPath`:
```
TypeError: argument of type 'WindowsPath' is not iterable
```
Fixes #215
> Fixed failing tests on Windows

- cookiecutter.json
#162 uses `ccds` instead of `cookiecutter`. We want to have an informative message that instructs people who try to use `cookiecutter` to either a) switch to using `ccds` b) an option to continue using the deprecated `cookiecutter`. This PR simply adds that command.
```
cookiecutter https://...@v1
```
does not work
> subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/r-b-g-b/cookiecutter-data-science@v1']' returned non-zero exit status 128.
since `git clone https://...@v1` fails.
Instead the cookiecutter docs state we can use
```
cookiecutter --help
-c, --checkout TEXT        branch, tag or commit to checkout after git clone
```
I tested this out on [my fork](https://github.com/r-b-g-b/cookiecutter-data-science) of this repo. I added a `v1` tag on `master` and a …
> Update suggestion to keep using deprecated cookiecutter template

- README.md
Small fix to the top level README since it was not coherent with the rest of the project and documentation.
> Added setup.py to project organization in README

- README.md
- hooks/pre_gen_project.py
Add deprecation message and instructions so that users can start migrating any automation that depends on calling `cookiecutter https://github.com/drivendata/cookiecutter-data-science`
> V1 tag and deprecation

- README.md
Quick update of the docs based on install to test
> docs: add dev-requirements, remove tox.ini

- LICENSE
- README.md
- ccds.json
- docs/docs/index.md
- tests/test_creation.py
- {{ cookiecutter.repo_name }}/Makefile
- {{ cookiecutter.repo_name }}/pyproject.toml
- {{ cookiecutter.repo_name }}/setup.cfg
- Adds formatting commands (`black`) and pre-commit wrapper
- Configuration file format defaults (`setup.cfg` and `pyproject.toml`)
- Support Python 3.8, remove 3.5
- Default to no license (rather than MIT)
> Lint, format, license

- Makefile
Adding create-environment command, global variables, and a few comments (making the Makefile for this project more like the Makefile it generates)
> Updating the Makefile

- hooks/pre_gen_project.py
Removing the deprecation message from the pre-rendering hook (and since there's nothing left, adding a pointer to the documentation)
Closes #281
> Removing deprecation message from v2

- Makefile
- ccds.json
- hooks/post_gen_project.py
- tests/conftest.py
- tests/test_creation.py
- {{ cookiecutter.repo_name }}/Makefile
- {{ cookiecutter.repo_name }}/{{ cookiecutter.module_name }}/data/make_dataset.py
Closes #49 
Provides additional prompt to make boilerplate python module files and folders disappear, with the exception of `__init__.py` to make the module a python module.
> Optionally remove boilerplate in initial setup

- .gitignore
- Makefile
- dev-requirements.txt
- docs/docs/css/extra.css
- docs/docs/index.md
- docs/docs/js/extra.js
- docs/mkdocs.yml
- docs/scripts/generate-termynal.py
Uses [mkdocs-termynal](https://github.com/mkdocs-plugins/termynal) to automatically create a new screencast recording when the docs build.
- Add [mkdocs-gen-files](https://github.com/oprypin/mkdocs-gen-files) to run scripts as part of the mkdocs build
- Add a script `docs/scripts/generate-termynal.py` to generate `docs/_partials/termynal.md` with the output from running CCDS.
- Use [mkdocs-include-markdown-plugin](https://github.com/mondeja/mkdocs-include-markdown-plugin) to incorporate the generated `docs/_partials/termynal.md` in `index.md`
- Add the `mkdocs-termynal` plugin to add replay for the terminal session in the docs.
- Add some CSS/JS tweaks to make things look nice and smooth.
Closes #314
> Create new screencast automatically on docs build

- tests/conda_harness.sh
- tests/pipenv_harness.sh
- tests/test_creation.py
- tests/virtualenv_harness.sh
- {{ cookiecutter.repo_name }}/Makefile
Closes #221
This PR switches the style and format of the python script in the Makefile that generates the help message text. The old script was not formatted correctly to regex match commented commands written with the structure we use in our Makefile, and leveraged `$$VAR` syntax in the command itself that does not work in Windows environments.
In order for this to work in the intended way, we had to treat the Python script as a single line - otherwise, because we're invoking the script as a command, newlines would trigger running a new command entirely. That's why the script ends each line with `; \`.
> Update Makefile help command to work on all platforms

- docs/docs/index.md
- docs/mkdocs.yml
- docs/scripts/generate-termynal.py
Closes #342 
This PR fixes a bug during screencast generation that left a stray `termynal.md` file that gets included in the docs tree and displayed as its own page. Instead, we use `mkdocs-gen-files` as intended with a temporary string filename rather than an explicit path, and we temporarily modify `index.md` in place during the build process to produce the final output.
> Fix screencast generation

- docs/docs/contributing.md
- docs/docs/css/extra.css
- docs/docs/index.md
- docs/docs/opinions.md
- docs/docs/related.md
- docs/docs/v1.md
- docs/docs/why.md
- docs/mkdocs.yml
This PR switches up the structure of the docs slightly so we use multiple pages instead of a long single page. It uses the material theme's `toc.integrate` feature to integrate table of contents with nav on the left as well as `navigation.instant` to we pre-fetch the page so it still feels somewhat single-pagey.
May not be strictly necessary to make these changes, so happy to close without merging if the current single-page approach suffices.
Closes #334
> Update docs to use multiple pages

- .github/workflows/tests.yml
- ccds/hook_utils/dependencies.py
- hooks/post_gen_project.py
- pyproject.toml
> Add workflows for Python 3.12

- docs/docs/css/extra.css
Fixes a few issues where render-deployed version looks different from local.
Specifically, this PR fixes:
* Border color on infobox
* Sizing of code blocks (min-width 35rem, but flexes to grow)
* Makes sizing of multi-tabbed menu same as underlying code box
> Minor CSS Tweaks

- .github/workflows/tests.yml
- README.md
- ccds/hook_utils/dependencies.py
- docs/docs/css/extra.css
- docs/docs/index.md
- docs/docs/opinions.md
- docs/docs/v1.md
- docs/overrides/partials/nav.html
- docs/scripts/configuration-table.py
- hooks/post_gen_project.py
- pyproject.toml
Per the comments, does the following:
- Lists packages for "basic" option (needed some refactoring to get those at docs render time)
- Have headers same width as body text
- Add link to announcement blog post at top of docs
- Update `tree` output at end of index page
- Update opinion pages formatting to be less varied
- Add DD footer to nav links
- Sets min Python version to 3.8
- Add miniconda, which was removed from MacOS images (see https://github.com/actions/runner-images/issues/9262 )
> Updates from review of V2 docs

- README.md
- ccds/__main__.py
- docs/docs/contributing.md
- docs/docs/index.md
- docs/docs/v1.md
- docs/mkdocs.yml
- docs/scripts/generate-termynal.py
- pyproject.toml
This PR updates links throughout the project to reflect updated ownership of the repo by the `drivendataorg` rather than the legacy `drivendata` user.
> Fix links throughout that reference old github user to reference new github org

- .github/workflows/tests.yml
- README.md
Closes #364 
For v2, we updated the directory structure in the docs site but not on the README page.
This PR also updates the test workflow so that the tests (which take a long time to run) don't run if _only_ the README is updated.
> Update directory structure in README

- HISTORY.md
- ccds/__main__.py
- hooks/post_gen_project.py
- tests/conda_harness.sh
- tests/pipenv_harness.sh
- tests/test_creation.py
- tests/test_functions.sh
- tests/virtualenv_harness.sh
- {{ cookiecutter.repo_name }}/{{ cookiecutter.module_name }}/__init__.py
- Remove config import from `__init__.py` (not needed and also breaks since it is there in non-scaffold scenario)
- Refactor some repeated code
- Add import and import config tests
- Add changelog
Closes #370
> Remove config import from init to fix scaffold usage

- {{ cookiecutter.repo_name }}/Makefile
A few tweaks to Makefile commands
- Added whitespace to `sync_data_down`
- Swapped order for `sync_data_up`
- Fix conditional profile logic in `sync_data_up` (so it matches `sync_data_down`)
- Fix path for `make data`
Closes #394 
Tested manually:
```
❯ ccds .
project_name (project_name):
repo_name (project_name):
module_name (project_name):
author_name (Your name (or your organization/company/team)):
description (A short description of the project.):
python_version_number (3.10):
Select dataset_storage
1 - none
2 - azure
3 - s3
4 - gcs
Choose from [1/2/3/4] (1): 3
bucket (bucket-name): drivendata-ccds-test
aws_profile (default):
Select environment_manager
1 - virtualenv
2 - conda
3 - pipenv
4 - none
Choose from [1/2/3/4] (1):
Select dependency_file
1 - requirements.txt
2 - …
```
> 394 makefile fixes

- {{ cookiecutter.repo_name }}/README.md
This PR fixes the directory tree in the README template.
It seems that the layout structure has changed with cookiecutter-data-science v2 thus the generated structure does not match the directory tree shown in the README.
I copy pasted the directory tree from the top-level README and pasted it into the template.
> Update directory tree in README template

- .github/workflows/release.yml
- HISTORY.md
- Makefile
- README.md
- RELEASING.md
- ccds/__init__.py
- ccds/__main__.py
- ccds/version.py
- docs/docs/all-options.md
- hooks/pre_gen_project.py
- hooks/pre_prompt.py
closes #317 
closes #389 
~**Do not merge** - [#315](https://github.com/drivendata/cookiecutter-data-science/issues/315) is needed first. After transfer, the repo should automatically have access to the PyPI secrets needed by `release.yml`~
Users can now see the version of `ccds` after importing (`ccds.__version__`). However, the *project* name is different than the *module* name. This means that in `version.py`, we have to hard code the project name with:
```python
__version__ = importlib_metadata.version("cookiecutter-data-science")
```
Instead of using:
```python
__version__ = importlib_metadata.version(__name__.split(".", 1)[0])
```
Per #389, we wanted a way to allow more stable behavior when someone installs ccds. Currently, any change to the template on the master branch will …
> Add release GitHub actions

- docs/README.md
> Remove reference to gh-pages deploy

- ccds-help.json
- ccds.json
- ccds/hook_utils/dependencies.py
- docs/scripts/generate-termynal.py
- hooks/post_gen_project.py
- tests/conda_harness.sh
- tests/conftest.py
- tests/pipenv_harness.sh
- tests/test_creation.py
- tests/virtualenv_harness.sh
- {{ cookiecutter.repo_name }}/.gitignore
- {{ cookiecutter.repo_name }}/Makefile
- {{ cookiecutter.repo_name }}/pyproject.toml
Closes #374
Closes #388 
This PR adds [ruff](https://docs.astral.sh/ruff/) as the default linting and formatting option for new ccds projects.
* I've slightly altered the Makefile command tests so that they now run within each venv harness. I check to ensure that linting and formatting run without error and that nothing is reformatted.
* For whatever reason, I found that ruff piped to stdout and flake8/black/isort piped to stderr. Maybe there's a nuance here or I've done something wrong?
* I've cleaned up the generated `pyproject.toml` and removed `setup.cfg` if using ruff since it's no longer needed. 
* I didn't stray very far from the default ruff config, changing only the line length. If we are opinionated about the default set of linting / formatting options, happy to add those, but I …
> Add ruff as default linting + formatting option

- {{ cookiecutter.repo_name }}/pyproject.toml
- {{ cookiecutter.repo_name }}/{{ cookiecutter.module_name }}/dataset.py
- {{ cookiecutter.repo_name }}/{{ cookiecutter.module_name }}/features.py
- {{ cookiecutter.repo_name }}/{{ cookiecutter.module_name }}/modeling/predict.py
- {{ cookiecutter.repo_name }}/{{ cookiecutter.module_name }}/modeling/train.py
- {{ cookiecutter.repo_name }}/{{ cookiecutter.module_name }}/plots.py
#387 changed our default behavior by removing configuration. This PR adds them back in. It also fixes #388 by using the correct names.
> Add back isort configuration that was removed in #387

- Makefile
- ccds-help.json
- ccds.json
- hooks/post_gen_project.py
- {{ cookiecutter.repo_name }}/Makefile
- {{ cookiecutter.repo_name }}/tests/pytest/test_data.py
- {{ cookiecutter.repo_name }}/tests/unittest/test_data.py
Closes #195
- Add an option for testing with pytest, unittest, or none.
- If a testing framework is selected, add a root-level `tests` directory with one failing test that tests that the code is tested
- Add a `make test` command
> Add option for tests

- .github/workflows/tests.yml
- docs/scripts/generate-termynal.py
When we added testing frameworks to the option set (#447) we did not update the terminal animation inputs so the last one was missing. This made the build fail because we `assert` that all options are present in the generated animation.
To prevent us missing this in the future, I've added building the docs to the `tests` workflow so that we'll fail if the docs do not properly generate.
> Fix terminal animation generation in docs build

- .github/workflows/tests.yml
- .gitignore
- Makefile
- ccds-help.json
- ccds.json
- ccds/hook_utils/dependencies.py
- hooks/post_gen_project.py
- tests/conftest.py
- tests/pixi_harness.sh
- tests/test_creation.py
- {{ cookiecutter.repo_name }}/.gitignore
- {{ cookiecutter.repo_name }}/Makefile
Adds support for pixi as an environment manager and `pixi.toml` as a dependency format.
- Add `pixi`
- Add `pixi.toml` as dependency format
- Support `pyproject.toml` with `pixi`
- Add pixi test harness
- Add pixi to CI
- Update documentation
Closes #406
> Support pixi as environment manager
